### PR TITLE
Update mysql install for ubuntu 16.04

### PR DESCRIPTION
**Pull request by jonathangreen**

### CODE REVIEW

**Comment by jonathangreen** [comment]
@mark-cooper This look reasonable to you?

**Comment by mark-cooper** [comment]
Yeah, looks good to me, although this highlights how we could benefit from some additional independent role testing. I don't think Travis has options for testing multiple OS environments (?). We could add a Vagrantfile, or look again at ServerSpec / Test Kitchen, but that's a bit more of a commitment.

But if you're happy with this as is now, then I am too.

**Comment by jonathangreen** [comment]
I believe travis is working on adding additional OS options.
https://docs.travis-ci.com/user/multi-os/

I think we could build on both ubuntu precise and trusty using travis.

**Comment by jonathangreen** [comment]
I'm happy this is working fairly well so I'm going to merge.

**Pull request merged**
